POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "UserIdTest3",
    "author": "String",
    "url": "String",
    "likes": 2,
    "user": "5a92f026598fb61ea05e2f77"
}